apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: mnrp
build:
  artifacts:
    - image: ghcr.io/gnur/tobab
      platforms:
        - linux/amd64
      context: .
      ko:
        labels:
          org.opencontainers.image.source: https://github.com/gnur/echoo
        dependencies:
          paths:
            - '**/*.go'
            - '**/*.html'
            - go.*
