apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: mnrp
build:
  tagPolicy:
    gitCommit:
      ignoreChanges: false
  artifacts:
    - image: ghcr.io/gnur/echoo
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
